import fs from 'fs';
import path from 'path';
import chalk from 'chalk';
import { loadRules, loadTraces } from '../lib/storage';
import { BusinessFlow, FlowStep, ConditionalStep, FinalScenarioStep, ProcessStep } from '../types';

interface ReportOptions {
  format: 'markdown' | 'html';
  output: string;
}

function buildFlowLines(flow: BusinessFlow): string[] {
  const lines: string[] = [];
  const visited = new Set<string>();

  function walk(stepId: string, depth: number): void {
    if (visited.has(stepId) || depth > 20) return;
    visited.add(stepId);
    const step = flow.steps.find((s: FlowStep) => s.id === stepId);
    if (!step) return;
    const indent = '  '.repeat(depth);

    if (step.type === 'conditional') {
      const s = step as ConditionalStep;
      lines.push(`${indent}- **${s.description}**`);
      lines.push(`${indent}  - ✅ Yes →`);
      walk(s.true_branch, depth + 2);
      lines.push(`${indent}  - ❌ No →`);
      walk(s.false_branch, depth + 2);
    } else if (step.type === 'process') {
      const s = step as ProcessStep;
      lines.push(`${indent}- ⚙️ ${s.description}`);
      walk(s.next, depth + 1);
    } else if (step.type === 'final_scenario') {
      const s = step as FinalScenarioStep;
      const icon = s.is_success ? '🟢' : '🔴';
      lines.push(`${indent}- ${icon} **${s.description}** \`HTTP ${s.expected_http_code}\``);
      if (s.error_category) lines.push(`${indent}  - Error: \`${s.error_category}\``);
    }
  }

  walk(flow.initial_step, 0);
  return lines;
}

function generateMarkdown(rules: ReturnType<typeof loadRules>, coverage: Map<string, number>): string {
  if (!rules) return '';

  const totalFlows = rules.flows.length;
  const coveredFlows = rules.flows.filter(f => f.steps.some(s => coverage.has(`${f.id}::${s.id}`))).length;
  const totalTraces = [...coverage.values()].reduce((a, b) => a + b, 0);

  const lines: string[] = [];
  lines.push(`# Business Rules — ${rules.project_name}`);
  lines.push('');
  lines.push(`> Generated by **QA Architect** on ${new Date(rules.generated_at).toLocaleString()}`);
  lines.push('');
  lines.push('## Summary');
  lines.push('');
  lines.push('| | |');
  lines.push('|---|---|');
  lines.push(`| Flows detected | **${totalFlows}** |`);
  lines.push(`| Flows with coverage | **${coveredFlows}** of ${totalFlows} |`);
  lines.push(`| Traces captured | **${totalTraces}** |`);
  lines.push('');
  lines.push('## Index');
  lines.push('');
  rules.flows.forEach((flow, i) => {
    const badge = flow.steps.some(s => coverage.has(`${flow.id}::${s.id}`)) ? ' ✅' : ' ⬜';
    lines.push(`${i + 1}. [${flow.name}](#flow-${i + 1})${badge}`);
  });
  lines.push('');
  lines.push('---');
  lines.push('');

  rules.flows.forEach((flow, i) => {
    const hasCoverage = flow.steps.some(s => coverage.has(`${flow.id}::${s.id}`));
    const successSteps = flow.steps.filter(s => s.type === 'final_scenario' && (s as FinalScenarioStep).is_success);
    const failSteps = flow.steps.filter(s => s.type === 'final_scenario' && !(s as FinalScenarioStep).is_success);

    lines.push(`## Flow ${i + 1}: ${flow.name} {#flow-${i + 1}}`);
    lines.push('');
    lines.push('| Field | Value |');
    lines.push('|---|---|');
    lines.push(`| Endpoint | \`${flow.http_method} ${flow.route}\` |`);
    lines.push(`| Method | \`${flow.controller_method}\` |`);
    lines.push(`| File | \`${flow.source_file}\` |`);
    lines.push(`| Coverage | ${hasCoverage ? '✅ Has real traces' : '⬜ No traces yet'} |`);
    lines.push(`| Success scenarios | ${successSteps.length} |`);
    lines.push(`| Failure scenarios | ${failSteps.length} |`);
    lines.push('');
    lines.push('### Decision tree');
    lines.push('');
    lines.push(...buildFlowLines(flow));
    lines.push('');

    if (failSteps.length > 0) {
      lines.push('### Failure scenarios');
      lines.push('');
      lines.push('| Description | HTTP | Error category |');
      lines.push('|---|---|---|');
      failSteps.forEach(s => {
        const fs = s as FinalScenarioStep;
        const count = coverage.get(`${flow.id}::${s.id}`) ?? 0;
        const cov = count > 0 ? ` *(${count} traces)*` : '';
        lines.push(`| ${fs.description}${cov} | \`${fs.expected_http_code}\` | \`${fs.error_category ?? '-'}\` |`);
      });
      lines.push('');
    }

    lines.push('---');
    lines.push('');
  });

  return lines.join('\n');
}

function generateHtml(rules: ReturnType<typeof loadRules>, coverage: Map<string, number>): string {
  if (!rules) return '';

  const totalFlows = rules.flows.length;
  const coveredFlows = rules.flows.filter(f => f.steps.some(s => coverage.has(`${f.id}::${s.id}`))).length;

  function renderStep(flow: BusinessFlow, stepId: string, depth: number, visited = new Set<string>()): string {
    if (visited.has(stepId) || depth > 20) return '';
    visited.add(stepId);
    const step = flow.steps.find((s: FlowStep) => s.id === stepId);
    if (!step) return '';

    if (step.type === 'conditional') {
      const s = step as ConditionalStep;
      return `<div class="step conditional"><span class="step-icon">◆</span><span class="step-label">${s.description}</span>
        <div class="branches">
          <div class="branch"><span class="branch-label yes">Yes</span>${renderStep(flow, s.true_branch, depth + 1, visited)}</div>
          <div class="branch"><span class="branch-label no">No</span>${renderStep(flow, s.false_branch, depth + 1, new Set(visited))}</div>
        </div></div>`;
    }
    if (step.type === 'process') {
      const s = step as ProcessStep;
      return `<div class="step process"><span class="step-icon">⚙</span><span class="step-label">${s.description}</span>${renderStep(flow, s.next, depth + 1, visited)}</div>`;
    }
    if (step.type === 'final_scenario') {
      const s = step as FinalScenarioStep;
      const count = coverage.get(`${flow.id}::${step.id}`) ?? 0;
      const badge = count > 0 ? `<span class="trace-badge">${count} traces</span>` : '';
      return `<div class="step scenario ${s.is_success ? 'success' : 'failure'}"><span class="step-icon">${s.is_success ? '✓' : '✗'}</span><span class="step-label">${s.description}</span><code class="http-code">${s.expected_http_code}</code>${badge}</div>`;
    }
    return '';
  }

  const flowCards = rules.flows.map((flow, i) => {
    const hasCoverage = flow.steps.some(s => coverage.has(`${flow.id}::${s.id}`));
    return `<section class="flow-card" id="flow-${i + 1}">
      <div class="flow-header">
        <h2>${flow.name}</h2>
        <div class="flow-meta"><code>${flow.http_method} ${flow.route}</code>
          <span class="coverage-badge ${hasCoverage ? 'covered' : 'uncovered'}">${hasCoverage ? '✅ Covered' : '⬜ No traces'}</span>
        </div>
        <div class="flow-source">${flow.source_file} → ${flow.controller_method}</div>
      </div>
      <div class="flow-tree">${renderStep(flow, flow.initial_step, 0)}</div>
    </section>`;
  }).join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Business Rules — ${rules.project_name}</title>
  <style>
    *{box-sizing:border-box;margin:0;padding:0}body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:#0f1117;color:#e2e8f0;line-height:1.6}
    header{background:#1a2035;border-bottom:1px solid #1e293b;padding:24px 40px}header h1{font-size:22px;font-weight:700}header p{color:#64748b;font-size:13px;margin-top:4px}
    .stats{display:flex;gap:24px;margin-top:16px}.stat{background:#0f1117;border:1px solid #1e293b;border-radius:8px;padding:12px 20px}
    .stat-value{font-size:24px;font-weight:700}.stat-label{font-size:11px;color:#64748b;text-transform:uppercase;letter-spacing:.05em}
    nav{background:#0a0e1a;border-right:1px solid #1e293b;width:240px;position:fixed;top:0;left:0;height:100vh;overflow-y:auto;padding-top:80px}
    nav a{display:block;padding:8px 16px;font-size:13px;color:#94a3b8;text-decoration:none;border-bottom:1px solid #1e293b}nav a:hover{background:#1a2035;color:#e2e8f0}
    main{margin-left:240px;padding:40px;padding-top:120px;max-width:900px}
    .flow-card{background:#1a2035;border:1px solid #1e293b;border-radius:12px;padding:24px;margin-bottom:32px}
    .flow-header h2{font-size:18px;font-weight:600;margin-bottom:8px}.flow-meta{display:flex;align-items:center;gap:12px;margin-bottom:6px}
    .flow-meta code{background:#0f1117;padding:3px 8px;border-radius:4px;font-size:12px;color:#60a5fa}
    .flow-source{font-size:11px;color:#475569;margin-bottom:20px}.coverage-badge{font-size:11px;padding:2px 8px;border-radius:4px}
    .coverage-badge.covered{background:#14532d;color:#4ade80}.coverage-badge.uncovered{background:#1e293b;color:#64748b}
    .flow-tree{border-top:1px solid #1e293b;padding-top:20px}
    .step{margin:8px 0 8px 16px;padding:10px 14px;border-radius:8px;border-left:3px solid}
    .step.conditional{background:#1c1a0f;border-color:#f59e0b}.step.process{background:#0f1a2a;border-color:#475569}
    .step.scenario.success{background:#0a1f12;border-color:#16a34a}.step.scenario.failure{background:#1a0a0a;border-color:#dc2626}
    .branches{display:flex;gap:16px;margin-top:10px;flex-wrap:wrap}.branch{flex:1;min-width:200px}
    .branch-label{font-size:11px;font-weight:600;display:block;margin-bottom:4px}.branch-label.yes{color:#4ade80}.branch-label.no{color:#f87171}
    .http-code{background:#0f1117;padding:1px 6px;border-radius:4px;font-size:11px;margin-left:8px;color:#94a3b8}
    .trace-badge{background:#1d4ed8;color:#fff;font-size:10px;padding:1px 6px;border-radius:4px;margin-left:8px}
    footer{text-align:center;color:#334155;font-size:12px;padding:40px;margin-left:240px}
  </style>
</head>
<body>
  <header>
    <h1>📋 ${rules.project_name} — Business Rules</h1>
    <p>Generated by QA Architect · ${new Date(rules.generated_at).toLocaleString()}</p>
    <div class="stats">
      <div class="stat"><div class="stat-value">${totalFlows}</div><div class="stat-label">Flows</div></div>
      <div class="stat"><div class="stat-value">${coveredFlows}</div><div class="stat-label">Covered</div></div>
      <div class="stat"><div class="stat-value">${totalFlows - coveredFlows}</div><div class="stat-label">No traces</div></div>
    </div>
  </header>
  <nav>${rules.flows.map((f, i) => `<a href="#flow-${i + 1}">${i + 1}. ${f.name}</a>`).join('')}</nav>
  <main>${flowCards}</main>
  <footer>Generated with QA Architect</footer>
</body>
</html>`;
}

export function reportCommand(options: ReportOptions): void {
  const projectRoot = process.cwd();
  const rules = loadRules(projectRoot);

  if (!rules) {
    console.error(chalk.red('No rules found. Run "qa-architect analyze" first.'));
    process.exit(1);
  }

  const tracesData = loadTraces(projectRoot);
  const coverage = new Map<string, number>();

  for (const trace of tracesData.traces) {
    if (trace.type !== 'http' || !trace.request || !trace.response) continue;
    const status = trace.response.status;
    for (const flow of rules.flows) {
      for (const step of flow.steps) {
        if (step.type !== 'final_scenario') continue;
        if ((step as FinalScenarioStep).expected_http_code === status) {
          const key = `${flow.id}::${step.id}`;
          coverage.set(key, (coverage.get(key) ?? 0) + 1);
        }
      }
    }
  }

  const outputPath = path.resolve(projectRoot, options.output);
  const content = options.format === 'html'
    ? generateHtml(rules, coverage)
    : generateMarkdown(rules, coverage);

  fs.writeFileSync(outputPath, content, 'utf-8');

  console.log(chalk.bold.green(`\n✔ Report generated`));
  console.log(chalk.gray(`  Format: ${options.format.toUpperCase()}`));
  console.log(chalk.gray(`  Output: ${outputPath}`));
  console.log(chalk.gray(`  Flows:  ${rules.flows.length}`));
}
